%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-kompass
Version:        0.3.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS kompass package

License:        MIT
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-pykdl
Requires:       ros-humble-automatika-ros-sugar
Requires:       ros-humble-kompass-interfaces
Requires:       ros-humble-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python3-pykdl
BuildRequires:  ros-humble-automatika-ros-sugar
BuildRequires:  ros-humble-kompass-interfaces
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Kompass: Event-driven navigation system

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/humble"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Fri Oct 03 2025 Automatika Robotics <contact@automatikarobotics.com> - 0.3.2-1
- Autogenerated by Bloom

* Tue Sep 02 2025 Automatika Robotics <contact@automatikarobotics.com> - 0.3.1-1
- Autogenerated by Bloom

* Wed Jul 02 2025 Automatika Robotics <contact@automatikarobotics.com> - 0.3.0-1
- Autogenerated by Bloom

* Tue Jan 28 2025 Automatika Robotics <contact@automatikarobotics.com> - 0.2.1-1
- Autogenerated by Bloom

